[project]
name = "video-cut"
version = "0.1.0"
description = "Video progress bar overlay tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.8.0",
    "moviepy>=1.0.3",
    "pillow>=10.0.0",
    "numpy>=1.24.0",
]
